cargo-features = ["codegen-backend"]
[package]
name = "social_networks"
version = "0.1.0"
edition = "2024"
authors = ["Valeriy Sakharov <valeratrades@gmail.com>"]
readme = "README.md"
license = "BlueOak-1.0.0"
repository = "https://github.com/valeratrades/social_networks"

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]

[dependencies]
ask_llm = "^2.1.0"
base64 = "^0.22"
clap = { version = "^4", features = ["derive"] }
clickhouse = { version = "^0.14", features = ["time"] }
color-eyre = "^0.6.5"
config = "^0"
derive-new = "^0"
futures = "0.3.31"
futures-util = "^0"
google-gmail1 = "^6"
grammers-client = "^0.8"
grammers-mtsender = "^0.8"
grammers-session = "^0.8"
grammers-tl-types = "^0.8"
hmac = "^0.12"
hyper = "^1"
hyper-rustls = "^0.27"
hyper-util = { version = "^0.1", features = ["client", "client-legacy", "http1"] }
imap = "3.0.0-alpha.15"
jiff = { version = "0.2.17", features = ["serde"] }
oauth1-request = "^0.6"
quick-xml = "0.38.4"
rand = "^0.9"
regex = "^1"
reqwest = { version = "^0", features = ["json"] }
rustls = { version = "^0.23", features = ["aws-lc-rs"] }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
sha1 = "^0.10"
tg = "^0.6"
tokio = { version = "^1", features = ["full"] }
tokio-tungstenite = { version = "^0", features = ["native-tls"] }
tracing = "^0"
tracing-appender = "^0"
tracing-subscriber = "^0"
xdg = { version = "3.0.0", features = ["serde"] }
yup-oauth2 = "12"

# my crates {{{
v_exchanges = { version = "0.16.7", default-features = false, features = ["binance"] }
v_utils = { version = "^2.15.9", features = ["xdg", "cli"] } #ga: rm path
#,}}}

[dev-dependencies]
insta = "1.45.0"

[lints.clippy]
# Stable
float_cmp = "allow" # is bad for `==` direct comparisons, but `<` and `>` should be allowed
len_zero = "allow" # `.empty()` is O(1) but on &str only
undocumented_unsafe_blocks = "warn"
tabs_in_doc_comments = "allow"

# Questionable
# const fns, so actually more performant
get_first = "allow"
get_last_with_len = "allow"
#,}}}
