cargo-features = ["codegen-backend"]
[package]
name = "social_networks"
version = "0.2.0"
edition = "2024"
authors = ["Valeriy Sakharov <valeratrades@gmail.com>"]
description = "my utils for social networks managing/monitoring"
readme = "README.md"
license = "BlueOak-1.0.0"
repository = "https://github.com/valeratrades/social_networks"

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }.tar.gz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[dependencies]
ask_llm = "^2.1.4"
base64 = "^0.22.1"
clap = { version = "^4.5.54", features = ["derive"] }
clickhouse = { version = "^0.14.2", features = ["time"] }
color-eyre = "^0.6.5"
colored = "^3"
config = "^0.15.19"
derive-new = "^0.7.0"
futures = "0.3.31"
futures-util = "^0.3.31"
google-gmail1 = "^7"
grammers-client = "^0.8"
grammers-mtsender = "^0.8"
grammers-session = "^0.8"
grammers-tl-types = "^0.8"
hmac = "^0.12"
hyper = "^1.8"
hyper-rustls = "^0.27"
hyper-util = { version = "^0.1.19", features = ["client", "client-legacy", "http1"] }
imap = "3.0.0-alpha.15"
jiff = { version = "0.2.18", features = ["serde"] }
oauth1-request = "^0.6"
quick-xml = "0.39.0"
rand = "^0.9"
regex = "^1.12.2"
reqwest = { version = "^0.13.1", features = ["json", "multipart", "query", "form"] }
rustls = { version = "^0.23.36", features = ["aws-lc-rs"] }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
sha1 = "^0.10"
tg = "^0.9"
tokio = { version = "^1", features = ["full"] }
tokio-tungstenite = { version = "^0", features = ["native-tls"] }
tracing = "^0"
tracing-appender = "^0"
tracing-subscriber = "^0"
xdg = { version = "3.0.0", features = ["serde"] }
yup-oauth2 = "12"

# my crates {{{
miette = { version = "7.6.0", features = ["fancy", "syntect-highlighter", "serde"] }
psm = "0.1.29"
v_exchanges = { version = "0.16.7", default-features = false, features = ["binance"] }
v_utils = { version = "^2.15.21", features = ["xdg", "cli", "tracing"] } #ga: rm path
#,}}}

[dev-dependencies]
insta = "1.46.1"

[lints.clippy]
# Stable
float_cmp = "allow" # is bad for `==` direct comparisons, but `<` and `>` should be allowed
len_zero = "allow" # `.empty()` is O(1) but on &str only
undocumented_unsafe_blocks = "warn"
tabs_in_doc_comments = "allow"

# Questionable
# const fns, so actually more performant
get_first = "allow"
get_last_with_len = "allow"
#,}}}
